### ISSUE TITLE
Angularjs example

### ISSUE THREAD

**Issue by annabellor** [katowulf/mockfirebase#50]
I'm really searching for an angularjs example, where can I use this, do I need to inject the $firebase and how to use it with a service?

Do some one have that for me? I'm new to firebase in combination with angularjs

**Comment by bendrucker** [comment]
I assume you're using AngularFire since you're referencing `$firebase`. You don't need to do anything special with MockFirebase + Angular and AngularFire's not actually involved here either. In your code you're calling `new Firebase`. You'll need to override `Firebase` with `MockFirebase`:

https://github.com/katowulf/mockfirebase/blob/master/tutorials/override.md

**Comment by annabellor** [comment]
I really don't know where to start, I have tried your suggestion but it's not working for me (see below). With $http angular service, you have an $httpBackend and you can stub your data (for testing purpose). With Mockfirebase I really don't know where to start/mock data, sorry for my noobness, but check this out.

This is my service:

```js
angular.module("myModule", ["firebase"]).factory("MyFirebaseService", function($firebase){
	var myFirebaseService, ref;
	
	ref = new Firebase("https://my-url.firebaseio.com").child("level1");
	
	//welcome is an object level with {title: "mockfire", content: "mockfire this 2 me"}
	myFirebaseService = {
		article1: $firebase(ref.child("welcome")).$asObject();
	};
	
	return myFirebaseService;
});
```

Test:
```js
describe("MyFirebaseService", function () {
    var mockService, firebaseMock;

    beforeEach(module("firebase", "myModule"));

    beforeEach(inject(function (MyFirebaseService, $firebase) {
        mockService = MyFirebaseService;
        firebaseMock = $firebase;
    }));

	it("should fetch data", function () {
		var article1, ref;

		MockFirebase.override();

		ref = new Firebase("https://my-url.firebaseio.com/").child("level1");
		ref.set("welcome"{
			"title": "mockfire",
			"content": "mockfire this 2 me"
		});
		
		article1= firebaseMock(reference.child("welcome")).$asObject();

		reference.flush();
		
		expect(article1.title).toBeDefined();
		expect(article1.title).toEqual("mockfire");
	});
});
```
and when I run it, I get this:

```js
Error: No deferred tasks to be flushed```
```

I want to know how I can test my services with stubdata and check if my article is filled or am I way off base with this :s.

Thanks for your time!

**Comment by bendrucker** [comment]
You're injecting the service before you do the overriding. You need to make sure `MockFirebase.override` is called before any code calls `Firebase`. If you go and inject `'MyFirebaseService'` in your test you're invoking `Firebase` before you call `override`.

**Comment by annabellor** [comment]
Thanks for the quick response, but it does not work for me... I miss something but I don't know what. Tried the following:

```js
describe("MyFirebaseService", function () {
    Mockfirebase.override();

    var mockService, firebaseMock;

    beforeEach(module("firebase", "myModule"));

   .... rest ommited
```

And

```js
describe("MyFirebaseService", function () {
    var mockService, firebaseMock;

    beforeEach(function(){
        Mockfirebase.override();
        module("firebase", "myModule")
    });

   .... rest ommited
```

Still the same errors :'(

**Comment by bendrucker** [comment]
Alright, well this is where I'll have to bow out then. This isn't related to MockFirebase and is more to do with standard testing patterns in JS. If your project is open source feel free to open an issue there and @ mention me.

**Comment by katowulf** [comment]
@annabellor, if you check out the test units for AngularFire, you'll see that we use this magic little mock to [inject MockFirebase in place of regular Firebase](https://github.com/firebase/angularfire/blob/master/tests/mocks/mocks.firebase.js). Any other issues you are having can also probably be resolved by looking at AngularFire's test units.

Cheers!

**Comment by annabellor** [comment]
Thanks for your time, it's not open source, so I can not mention you. But if you have the time to look at it via, eg teamviewer, let me know!

**Comment by annabellor** [comment]
@bendrucker and @katowulf 
Thanks for the help, I have something, but I don't know if this is the right way to read my stubbed data.

This is a piece of the data in firebase:
```js
{
    "level1": {
        "welcome": {
            "title": "Mockfire",
            "content": "This is content. This is content. This is content."
        }
    }
}
```

I have added a ref() to the object.
```js
angular.module("myModule", ["firebase"]).factory("MyFirebaseService", function($firebase){
	var myFirebaseService, ref;
	
	reference = new Firebase("https://my-url.firebaseio.com").child("level1");
	
	myFirebaseService = {
		ref: function () {
			return reference;
		}
		article1: $firebase(ref.child("welcome")).$asObject();
	};
	
	return myFirebaseService;
});
```

In my test folder, I add the mockfirebase:
```js
angular.module("mock.firebase", [])
	.run(function() {
		$window.MockFirebase.override();
	});
```

This is the actual test
```js
describe("MyFirebaseService", function () {
    var mockService, firebaseMock;

    beforeEach(module("mock.firebase", "myModule"));

    beforeEach(inject(function ($firebase, MyFirebaseService) {
        mockService = MyFirebaseService;
        firebaseMock = $firebase;
    }));

	it("should fetch data", function () {
		var welcome, ref;
		
		welcome = mockService.getWelcome;

		ref = mockService.ref().child("level1");
		
		ref.set("welcome"{
			"title": "mockfire",
			"content": "mockfire this 2 me"
		});
		
		ref.flush();
		
		expect(welcome.$$conf.inst._ref.getData().title).toBeDefined();
		expect(welcome.$$conf.inst._ref.getData().title).toEqual("mockfire");
	});
});
```

When I do this: ```welcome.$$conf.inst._ref.getData()``` instead of ```welcome.title```, it works. I see the actual stubbed data.

**Comment by annabellor** [comment]
Thanks for your input katowulf. Idd getWelcome is not there, changed it.

I'm not following the Thinkster.io tutorial, they never have worked for me. But do you mean the factory or the object that i'm returning in the factory?
