### ISSUE TITLE
Stubbed data object with an array is an object instead of an array

### ISSUE THREAD

**Issue by ghost** [katowulf/mockfirebase#51]
Me again :).

Maybe you can clarify this for me, when I have stubbed data like this:

``` js
var ref = ....;

ref.set({
    "level1": {
        "welcome": {
            "title": "Mockfire",
            "content": "This is content. This is content. This is content.",
            "mockarray": [
                "one",
                "two",
                "three"
            ]
        }
    }
});

ref.flush();
```

Where `ref.getData().level1.welcome.mockarray` is an object instead of an array, I can not use the array functions (like length, etc). I expected it to be an array. Is this correct or an bug? And if it's correct, why?

With the $httpBackend mock from angular, the same data (`level1.welcome.mockarray`) would be an array.

**Comment by annabellor** [comment]
Yes I saw that, I hoped mockfirebase would support it, but I understand why not. Thanks!

For the folks that want an array, just create it your self. Let (mock)firebase be it's self and you can do create stuff you want/need.
