### ISSUE TITLE
Strange $ signs in error messages

### ISSUE THREAD

**Issue by katowulf** [katowulf/mockfirebase#52]
Several of the assertion errors incorrectly include a `$` in front of the method names. Also, they should have `()` at the end. For example:

> AssertionError: First argument must be an object when calling $update

Should probably be:

> AssertionError: First argument must be an object when calling update()

**Comment by bendrucker** [comment]
I only found an issue with `update`. What was `$update` is now `"update"`. My preferred documentation is to always use the JavaScript meaning of "call," meaning that you call a function reference and not `fn()`. Nitpicky semantics aside, the important convention is that you then have the ability to use parentheses and clearly express expected arguments (e.g. the method headers in the API ref).
