### ISSUE TITLE
.parent() always returns null

### ISSUE THREAD

**Issue by maverickcoder** [katowulf/mockfirebase#53]
I create a new mockfirebase instance and pass json to default to. I can then use getData which shows the whole structure is present. 

I then use .child to navigate to a sub path, eg ('/child1/child2');

I then use .parent() to attempt to get to ('/child1') but it always just returns null.

Is this a bug, or any advice please?

Thanks. Ed

**Comment by bendrucker** [comment]
Please post code that reproduces this, not fragments of the calls
