### ISSUE TITLE
Basic tutorial doesn't work out of the box

### ISSUE THREAD

**Issue by Grety** [katowulf/mockfirebase#66]
MockFirebase.override() doesn't seem to exist

**Comment by katowulf** [comment]
Not enough detail here to repro issue. It [clearly exists](https://github.com/katowulf/mockfirebase/blob/master/browser/mockfirebase.js#L11523).

**Comment by bendrucker** [comment]
There are even smoke tests against it:

https://github.com/katowulf/mockfirebase/blob/master/test/smoke/globals.js

It's only in the browser build.

**Comment by Grety** [comment]
Am I getting something wrong? the tutorial clearly states:
npm install MockFirebase
var MockFirebase = require('MockFirebase').MockFirebase;
However MockFirebase.override() is not accessible.
I'm using it from Node.js 0.10.35

**Comment by katowulf** [comment]
Once again, not enough detail. What tutorial? Where? I've looked through everything in tutorials/ and the readme and not found any such instructions.

I did find [this in the tutorials](https://github.com/katowulf/mockfirebase), however, which is linked in the readme, and explains that override() is for Firebase on the window object, which would preclude usage in node.

Please provide enough detail so we can understand what you're driving at here and determine if there is something to fix.

**Comment by Grety** [comment]
Although, as you mentioned, it can be inferred from the reading more docs that it replaces window.Firebase, and thus cannot be used in Node.js, this [Basics Tutorial](https://github.com/katowulf/mockfirebase/blob/master/tutorials/basic.md) doesn't show this evidently. And a tutorial exists for stating basic things. So I still insist that it this .md file that should be corrected. 
I was on that page in 45 seconds after I learned about MockFirebase's existence but it took me about half an hour to sort things out with .override() because 'Basics Tutorial' doesn't actually contain basics. This tutorial works fine in Node.js too with the exclusion of .override() call, so why not just describe the matter fro those who might need it and ease the learning curve?

**Comment by bendrucker** [comment]
https://github.com/katowulf/mockfirebase/blob/master/tutorials/proxyquire.md

**Comment by katowulf** [comment]
Thanks for the link, that certainly clarifies things a bit. So you read through the Basics Tutorial under the assumption that it applied to node.js. Appreciate both the feedback and the time you took to report the issue. Hopefully Ben's fix will help others from running into the same confusion. Cheers.

**Comment by Grety** [comment]
Thanks for update! Looks like project is alive and the team reacts in a timely fashion! 
I will continue to post more as long as  I encounter. I've got a couple of more serious issues already
