### ISSUE TITLE
Validate event names

### ISSUE THREAD

**Issue by Grety** [katowulf/mockfirebase#68]
When trying to subscribe (with `.on()` or `.once()`) on a MockFirebase object with a wrong event name get a misleading error `Uncaught TypeError: Cannot read property 'push' of undefined`

**Comment by bendrucker** [comment]
Just notes for me here, I'll fix this. Firebase logs:

> Error: Query.on failed: First argument must be a valid event type: "value", "child_added", "child_removed", "child_changed", or "child_moved".
