### ISSUE TITLE
changeAuthState does not trigger resolution for authWithOAuth

### ISSUE THREAD

**Issue by ajcrites** [katowulf/mockfirebase#86]
I'm using angularfire and have `$firebaseAuth(ref).$authWithOAuthPopup` called.

    .then(authData => sessionAuth = authData)
    .then(auth.createUser)

This works in my app, but I want to be able to test the user's login.  In my test, I have:

    authService.doPopup();
    authService.ref.changeAuthState({uid: "test"});
    authService.ref.flush();
    expect(auth.createUser).to.have.been.called;

However, `auth.createUser` is *not* called.  `.then` is not being called.  After some digging, I've found that AngularFire *does* seem to be resolving the deferred internally but this doesn't propagate to `.then` being called.

Am I doing something incorrectly / is there a better way to do this test, or is this just an issue?

**Comment by bendrucker** [comment]
You need to call `$timeout.flush()` after injecting `$timeout`. Otherwise Angular won't try to resolve the promise. This is a general Angular testing requirement and not specific to MockFirebase.
