### ISSUE TITLE
Lacking support for `limitToFirst()` and `limitToLast()`

### ISSUE THREAD

**Issue by dylanjha** [katowulf/mockfirebase#92]
The Firebase javascript library prints Deprecation warnings for `limit()`. Consumers of the client library should be using `limitToFirst()` and `limitToLast()` instead

**Comment by bendrucker** [comment]
See #83. I put all work on this on pause. Just don't have the time for it right now. Would love to support 2.0 queries but I'm not able to spare the dozens of hours needed to make it happen right now.

**Comment by dylanjha** [comment]
@bendrucker thanks for the update!
